// biome-ignore-all lint/complexity/useLiteralKeys: Parsed JSON is a strict record.
import {
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

type JsonRecord = Record<string, unknown>;

export const CANONICAL_FILE = "AGENTS.md";
export const SYNC_SCRIPT = "rules:sync";
export const GUARD_SCRIPT = "rules:check";
export const GUARD_CONTRACT = "scripts/template/agent-rules-contract.ts";
export const GUARD_ENTRYPOINT = "scripts/template/validate-agent-rules.ts";
export const SYNC_ENTRYPOINT = "scripts/template/sync-agent-rules.ts";
export const DELEGATION_SOURCE =
	"scripts/template/agent-rules/archive-delegation.md";

// The OpenSpec marker, the CLI, and its injection point. This module is CORE —
// it is copied into every rendered project — so it cannot import the
// capability-gated OpenSpec contract that resolves the same binary, and the
// package name is assembled at runtime because it is a declared capability
// signature TOKEN: spelled literally here it would fail the anti-residue scan of
// every render that has no OpenSpec, with no way to fence it.
const OPENSPEC_MARKER = "openspec/config.yaml";
const OPENSPEC_PACKAGE = ["@fission-ai", "openspec"].join("/");
const CLI_RELATIVE = "node_modules/.bin/openspec";
const CLI_OVERRIDE = "OPENSPEC_BIN";
const SETUP_ARGV = ["artifact-experimental-setup"];
const QUIET_ENVIRONMENT: Record<string, string> = {
	OPENSPEC_TELEMETRY: "0",
	DO_NOT_TRACK: "1",
	CI: "true",
};

// The vendor's own archive procedure: a dated directory move, performed by the
// agent. Assembled rather than written so this guard is not itself a match for
// the scan it runs — a rule that needs a path exemption is a hole somebody
// eventually widens.
const FORBIDDEN_VENDOR_PROCEDURE = ["mv", "openspec/changes"].join(" ");

/**
 * The fourteen artifacts the pinned CLI generates for Claude.
 *
 * They are committed rather than produced at container create, because a
 * generator that runs on every create is a set of slash commands nobody
 * reviewed. They are regenerated by SPAWNING the CLI: the package's exports map
 * publishes `"."` only, so a deep import of its generator fails under Bun.
 */
export const VENDOR_ARTIFACTS = [
	".claude/commands/opsx/apply.md",
	".claude/commands/opsx/archive.md",
	".claude/commands/opsx/continue.md",
	".claude/commands/opsx/explore.md",
	".claude/commands/opsx/ff.md",
	".claude/commands/opsx/new.md",
	".claude/commands/opsx/sync.md",
	".claude/skills/openspec-apply-change/SKILL.md",
	".claude/skills/openspec-archive-change/SKILL.md",
	".claude/skills/openspec-continue-change/SKILL.md",
	".claude/skills/openspec-explore/SKILL.md",
	".claude/skills/openspec-ff-change/SKILL.md",
	".claude/skills/openspec-new-change/SKILL.md",
	".claude/skills/openspec-sync-specs/SKILL.md",
];

// The two artifacts whose BODY is replaced rather than merely headed. Both
// describe archiving, and the vendor's description of archiving is a procedure
// this repository forbids.
export const REPLACED_ARTIFACTS = [
	".claude/commands/opsx/archive.md",
	".claude/skills/openspec-archive-change/SKILL.md",
];

// Line-based HTML comments, matching the renderer's own fence syntax. They are
// comments so every mirror stays valid Markdown, and they are line based
// because `filterCapabilityBlocks` is a line filter: a marker that had to span
// lines would survive a render that dropped one of them.
const SHARED_START = /^<!--\s*shared:start\s+([a-z0-9-]+)\s*-->$/;
const SHARED_END = /^<!--\s*shared:end\s+([a-z0-9-]+)\s*-->$/;
const GENERATED_START = /^<!--\s*generated:start\s+([a-z0-9-]+)\s*-->$/;
const GENERATED_END = /^<!--\s*generated:end\s+([a-z0-9-]+)\s*-->$/;

/**
 * The required agent surfaces, including the one that is a NEGATIVE requirement.
 *
 * Codex's entry is the reason this is a table rather than a glob. "Codex reads
 * the root AGENTS.md and nothing else" is a standing decision, and a decision
 * that lives only in somebody's memory is re-litigated the first time a
 * generator offers to write `.codex/skills/openspec-*`. Recorded here it is a
 * check: `.codex/**` may not name an OpenSpec artifact, and adding one fails.
 */
export interface AgentSurface {
	agent: string;
	/** Where this agent's own rules live, or `AGENTS.md` when it has none. */
	file: string;
	/** Canonical blocks this file mirrors, in order. */
	blocks: string[];
	/** Directory this agent owns, if any. */
	directory?: string;
	/** Whether this agent receives the generated OpenSpec command/skill set. */
	openspecArtifacts: boolean;
}

export const AGENT_SURFACES: AgentSurface[] = [
	{
		agent: "shared",
		file: CANONICAL_FILE,
		blocks: [],
		openspecArtifacts: false,
	},
	{
		agent: "claude",
		file: "CLAUDE.md",
		blocks: ["openspec-lifecycle", "graphify-rules"],
		directory: ".claude",
		openspecArtifacts: true,
	},
	{
		agent: "claude-project",
		file: ".claude/CLAUDE.md",
		blocks: ["graphify-skill"],
		directory: ".claude",
		openspecArtifacts: true,
	},
	{
		agent: "gemini",
		file: "GEMINI.md",
		blocks: ["openspec-lifecycle", "graphify-rules"],
		directory: ".gemini",
		openspecArtifacts: false,
	},
	{
		agent: "codex",
		file: CANONICAL_FILE,
		blocks: [],
		directory: ".codex",
		openspecArtifacts: false,
	},
];

// The heading each generated region gets when `rules:sync` has to create it.
// Kept beside the block ids so a new block cannot be added without deciding
// what the mirrors call it.
export const BLOCK_HEADINGS: Record<string, string> = {
	"openspec-lifecycle": "## OpenSpec Lifecycle Ownership",
	"graphify-rules": "## graphify",
	"graphify-skill": "# graphify",
};

// The capability fence each block sits inside, so a generated region can be
// fenced exactly as its canonical source is. A block with no entry is core.
export const BLOCK_CAPABILITIES: Record<string, string> = {
	"openspec-lifecycle": "openspec",
	"graphify-rules": "graphify",
	"graphify-skill": "graphify",
};

// What an OpenSpec artifact looks like in a path or in prose. `.codex/**` may
// contain neither.
const OPENSPEC_ARTIFACT_TOKENS = ["opsx", "openspec-"];

function textOf(path: string): string {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return "";
	}
}

function exists(path: string): boolean {
	try {
		statSync(path);
		return true;
	} catch {
		return false;
	}
}

function filesUnder(directory: string, depth = 0): string[] {
	if (depth > 8) return [];
	const found: string[] = [];
	try {
		for (const entry of readdirSync(directory, { withFileTypes: true })) {
			const path = join(directory, String(entry.name));
			if (entry.isDirectory()) found.push(...filesUnder(path, depth + 1));
			else if (entry.isFile()) found.push(path);
		}
	} catch {
		return [];
	}
	return found.sort();
}

// Tracked files containing a literal, via git when it is there and a bounded
// walk when it is not. `git grep` is the right scope as well as the fast one:
// the rule is about what this repository SAYS, and an untracked scratch file
// says nothing to anybody.
function grepTracked(root: string, needle: string): string[] {
	const result = Bun.spawnSync(
		["git", "-C", root, "grep", "-lI", "-F", "-e", needle],
		{ stdout: "pipe", stderr: "pipe" },
	);
	if (result.exitCode === 0)
		return result.stdout.toString().split("\n").filter(Boolean).sort();
	if (result.exitCode === 1) return [];
	const found: string[] = [];
	for (const directory of [".claude", ".codex", ".gemini", "scripts", "docs"]) {
		for (const path of filesUnder(resolve(root, directory))) {
			if (textOf(path).includes(needle))
				found.push(path.slice(root.length + 1));
		}
	}
	for (const name of readdirSync(root)) {
		if (!name.endsWith(".md")) continue;
		if (textOf(resolve(root, name)).includes(needle)) found.push(name);
	}
	return found.sort();
}

function collect(
	source: string,
	start: RegExp,
	end: RegExp,
	label: string,
): { blocks: Map<string, string>; errors: string[] } {
	const blocks = new Map<string, string>();
	const errors: string[] = [];
	let open: string | undefined;
	let body: string[] = [];
	for (const line of source.split("\n")) {
		const opened = start.exec(line.trim());
		const closed = end.exec(line.trim());
		if (opened?.[1]) {
			if (open) errors.push(`agent-rules: nested ${label} block ${opened[1]}`);
			open = opened[1];
			body = [];
			continue;
		}
		if (closed?.[1]) {
			if (open !== closed[1]) {
				errors.push(`agent-rules: mismatched ${label} block ${closed[1]}`);
				open = undefined;
				continue;
			}
			if (blocks.has(open))
				errors.push(`agent-rules: duplicate ${label} block ${open}`);
			blocks.set(open, body.join("\n").trim());
			open = undefined;
			continue;
		}
		if (open) body.push(line);
	}
	if (open) errors.push(`agent-rules: unterminated ${label} block ${open}`);
	return { blocks, errors };
}

/** The canonical blocks `AGENTS.md` declares. */
export function sharedBlocks(source: string): {
	blocks: Map<string, string>;
	errors: string[];
} {
	return collect(source, SHARED_START, SHARED_END, "shared");
}

/** The generated mirror regions a rule file carries. */
export function generatedBlocks(source: string): {
	blocks: Map<string, string>;
	errors: string[];
} {
	return collect(source, GENERATED_START, GENERATED_END, "generated");
}

function fenced(id: string, body: string): string[] {
	const capability = BLOCK_CAPABILITIES[id];
	const lines: string[] = [];
	if (capability) lines.push(`<!-- capability:start ${capability} -->`);
	if (BLOCK_HEADINGS[id]) lines.push(BLOCK_HEADINGS[id] as string, "");
	lines.push(
		`<!-- generated:start ${id} -->`,
		body,
		`<!-- generated:end ${id} -->`,
	);
	if (capability) lines.push(`<!-- capability:end ${capability} -->`);
	return lines;
}

/**
 * Rewrite one mirror file's generated regions from the canonical blocks.
 *
 * Regions that already exist are replaced in place, so a mirror keeps whatever
 * of its own it has around them. A declared region that is missing is appended
 * with its heading and capability fence — bootstrapping is the same operation
 * as maintenance, which is what makes `rules:sync` idempotent.
 */
export function renderMirror(
	existing: string,
	surface: AgentSurface,
	canonical: Map<string, string>,
): string {
	const wanted = surface.blocks.filter((id) => canonical.has(id));
	const output: string[] = [];
	const seen = new Set<string>();
	let open: string | undefined;
	for (const line of existing.split("\n")) {
		const opened = GENERATED_START.exec(line.trim());
		const closed = GENERATED_END.exec(line.trim());
		if (opened?.[1]) {
			open = opened[1];
			const body = canonical.get(open);
			if (body !== undefined && wanted.includes(open)) {
				output.push(line, body);
				seen.add(open);
			}
			continue;
		}
		if (closed?.[1]) {
			if (open === closed[1] && seen.has(open)) output.push(line);
			open = undefined;
			continue;
		}
		if (!open) output.push(line);
	}
	let rendered = output
		.join("\n")
		.replace(/\n{3,}/g, "\n\n")
		.trimEnd();
	for (const id of wanted) {
		if (seen.has(id)) continue;
		rendered = `${rendered}\n\n${fenced(id, canonical.get(id) as string).join("\n")}`;
	}
	return `${rendered.trimEnd()}\n`;
}

// The overlay, stated as data. It is deliberately the smallest thing that can
// be checked: a header on every file saying where it came from and how to
// regenerate it, plus a body replacement on the two archive surfaces. Anything
// larger and "regenerated from the pinned CLI" stops being true.
function overlayHeader(): string[] {
	return [
		`<!-- Generated from ${OPENSPEC_PACKAGE} by \`openspec ${SETUP_ARGV[0]}\`. -->`,
		`<!-- Canonical rules live in ${CANONICAL_FILE}. Regenerate with \`bun run ${SYNC_SCRIPT}\`; never edit by hand. -->`,
	];
}

/**
 * Apply this repository's declared overlay to one vendor artifact.
 *
 * The header goes AFTER the YAML frontmatter, not before it: these files are
 * read as frontmatter-plus-body, and a comment above the opening `---` makes
 * the frontmatter invisible to every reader of it.
 */
export function overlayArtifact(
	path: string,
	vendor: string,
	delegation: string,
): string {
	const lines = vendor.replace(/\r\n/g, "\n").split("\n");
	let bodyStart = 0;
	if (lines[0]?.trim() === "---") {
		const close = lines.findIndex(
			(line, index) => index > 0 && line.trim() === "---",
		);
		bodyStart = close < 0 ? 0 : close + 1;
	}
	const frontmatter = lines.slice(0, bodyStart);
	const body = REPLACED_ARTIFACTS.includes(path)
		? delegation.trim().split("\n")
		: lines
				.slice(bodyStart)
				.join("\n")
				.replace(/^\n+/, "")
				.trimEnd()
				.split("\n");
	return `${[...frontmatter, "", ...overlayHeader(), "", ...body].join("\n").trimEnd()}\n`;
}

export interface VendorRegeneration {
	files: Map<string, string>;
	errors: string[];
}

/**
 * Regenerate the fourteen artifacts by spawning the pinned CLI into a scratch
 * directory, then applying the overlay.
 *
 * Nothing here touches this repository's own `.claude`: the CLI writes into a
 * temporary tree seeded with a copy of `openspec/config.yaml`, so a generator
 * that decided to write somewhere unexpected cannot damage the checkout it was
 * asked to describe.
 */
export function regenerateVendorArtifacts(root: string): VendorRegeneration {
	const files = new Map<string, string>();
	const errors: string[] = [];
	const binary = process.env[CLI_OVERRIDE] ?? resolve(root, CLI_RELATIVE);
	if (!exists(binary)) {
		return {
			files,
			errors: [
				`agent-rules: the pinned OpenSpec CLI is missing at ${binary}; run \`bun install\``,
			],
		};
	}
	const delegation = textOf(resolve(root, DELEGATION_SOURCE));
	if (delegation.trim() === "")
		errors.push(`agent-rules: ${DELEGATION_SOURCE} is missing or empty`);
	const scratch = mkdtempSync(join(tmpdir(), "openspec-artifacts-"));
	try {
		mkdirSync(join(scratch, "openspec"), { recursive: true });
		writeFileSync(
			join(scratch, OPENSPEC_MARKER),
			textOf(resolve(root, OPENSPEC_MARKER)),
		);
		const result = Bun.spawnSync([binary, ...SETUP_ARGV], {
			cwd: scratch,
			env: { ...process.env, ...QUIET_ENVIRONMENT },
			stdin: "ignore",
			stdout: "pipe",
			stderr: "pipe",
		});
		if (result.exitCode !== 0) {
			errors.push(
				`agent-rules: \`openspec ${SETUP_ARGV[0]}\` exited ${result.exitCode}: ${result.stderr.toString().trim().split("\n").at(-1) ?? ""}`,
			);
			return { files, errors };
		}
		for (const path of VENDOR_ARTIFACTS) {
			const produced = join(scratch, path);
			if (!exists(produced)) {
				errors.push(
					`agent-rules: the pinned CLI did not generate ${path}; the artifact set has changed`,
				);
				continue;
			}
			files.set(path, overlayArtifact(path, textOf(produced), delegation));
		}
	} finally {
		rmSync(scratch, { recursive: true, force: true });
	}
	return { files, errors };
}

/** Every mirror this tree should carry, with its rendered content. */
export function planMirrors(
	root: string,
	canonical: Map<string, string>,
): Array<{ surface: AgentSurface; path: string; content: string }> {
	const plan: Array<{ surface: AgentSurface; path: string; content: string }> =
		[];
	for (const surface of AGENT_SURFACES) {
		if (surface.file === CANONICAL_FILE || surface.blocks.length === 0)
			continue;
		const path = resolve(root, surface.file);
		if (!exists(path)) continue;
		plan.push({
			surface,
			path,
			content: renderMirror(textOf(path), surface, canonical),
		});
	}
	return plan;
}

// A canonical line worth checking for duplication: prose, not blank lines,
// fences, headings or list punctuation. Short lines are excluded because a
// two-word line is not evidence of a restated rule.
function normativeLines(body: string): string[] {
	return body
		.split("\n")
		.map((line) => line.trim())
		.filter(
			(line) =>
				line.length > 40 &&
				!line.startsWith("<!--") &&
				!line.startsWith("#") &&
				!line.startsWith("```"),
		);
}

/**
 * The whole cross-agent rules contract.
 *
 * The mirrors are checked against the canonical file rather than against each
 * other, and only for blocks the canonical file still declares — so a rendered
 * project that disabled a capability loses the canonical block and its mirrors
 * together, and the guard stays true in both trees without a second fence.
 */
export async function validateAgentRulesContract(
	root = resolve(import.meta.dir, "../.."),
	options: { vendor?: boolean } = {},
): Promise<string[]> {
	const errors: string[] = [];
	const canonicalPath = resolve(root, CANONICAL_FILE);
	if (!exists(canonicalPath)) {
		return [`agent-rules: ${CANONICAL_FILE} is missing`];
	}
	const canonicalSource = textOf(canonicalPath);
	const canonical = sharedBlocks(canonicalSource);
	errors.push(...canonical.errors);
	if (canonical.blocks.size === 0) {
		errors.push(
			`agent-rules: ${CANONICAL_FILE} declares no shared block; the mirrors would be checked against nothing`,
		);
	}
	for (const [id, body] of canonical.blocks) {
		if (body.trim() === "")
			errors.push(`agent-rules: the shared block ${id} is empty`);
		if (!(id in BLOCK_HEADINGS))
			errors.push(
				`agent-rules: the shared block ${id} has no declared heading`,
			);
	}

	const isTemplateRepository = exists(
		resolve(root, "template-parameters.toml"),
	);
	for (const surface of AGENT_SURFACES) {
		if (surface.file === CANONICAL_FILE) continue;
		const path = resolve(root, surface.file);
		if (!exists(path)) {
			// Absence is governed by the artifact rules, which the render tests
			// cover. In THIS repository every surface must exist.
			if (isTemplateRepository)
				errors.push(`agent-rules: ${surface.file} is missing`);
			continue;
		}
		const source = textOf(path);
		const mirror = generatedBlocks(source);
		errors.push(...mirror.errors.map((error) => `${error} in ${surface.file}`));
		const expected = surface.blocks.filter((id) => canonical.blocks.has(id));
		const actual = [...mirror.blocks.keys()];
		for (const id of actual) {
			if (!expected.includes(id))
				errors.push(
					`agent-rules: ${surface.file} carries the generated region ${id}, which ${CANONICAL_FILE} does not declare for it`,
				);
		}
		for (const id of expected) {
			if (!mirror.blocks.has(id)) {
				errors.push(
					`agent-rules: ${surface.file} is missing the generated region ${id}; run \`bun run ${SYNC_SCRIPT}\``,
				);
				continue;
			}
			if (mirror.blocks.get(id) !== canonical.blocks.get(id)) {
				errors.push(
					`agent-rules: ${surface.file} has drifted from ${CANONICAL_FILE} in ${id}; run \`bun run ${SYNC_SCRIPT}\``,
				);
			}
		}
		// Duplicate normative text. A rule restated outside its generated region
		// is a second rule the moment somebody edits one of the two copies, and
		// `rules:sync` would not touch it.
		const outside = renderMirror(source, surface, new Map()).split("\n");
		for (const id of expected) {
			for (const line of normativeLines(canonical.blocks.get(id) as string)) {
				if (outside.some((candidate) => candidate.trim() === line))
					errors.push(
						`agent-rules: ${surface.file} restates canonical text from ${id} outside its generated region`,
					);
			}
		}
	}

	// The negative requirement. Codex's whole surface is the root AGENTS.md.
	for (const surface of AGENT_SURFACES) {
		if (surface.openspecArtifacts || !surface.directory) continue;
		const directory = resolve(root, surface.directory);
		if (!exists(directory)) continue;
		for (const path of filesUnder(directory)) {
			const content = textOf(path);
			for (const token of OPENSPEC_ARTIFACT_TOKENS) {
				if (!content.includes(token)) continue;
				errors.push(
					`agent-rules: ${path.slice(root.length + 1)} names the OpenSpec artifact token "${token}", but ${surface.agent} receives no OpenSpec artifacts`,
				);
			}
		}
	}

	// The generated Claude artifacts. Presence is decided by the OpenSpec
	// marker — the capability's own artifact — so there is no skip anywhere: a
	// tree with the marker must carry all fourteen and they must equal a fresh
	// regeneration; a tree without it must carry none.
	const openspecEnabled = exists(resolve(root, OPENSPEC_MARKER));
	if (!openspecEnabled) {
		for (const path of [...VENDOR_ARTIFACTS, DELEGATION_SOURCE]) {
			if (exists(resolve(root, path)))
				errors.push(
					`agent-rules: ${path} exists in a project that has no ${OPENSPEC_MARKER}`,
				);
		}
	} else if (options.vendor !== false) {
		const regenerated = regenerateVendorArtifacts(root);
		errors.push(...regenerated.errors);
		for (const [path, content] of regenerated.files) {
			if (!exists(resolve(root, path))) {
				errors.push(
					`agent-rules: ${path} is missing; run \`bun run ${SYNC_SCRIPT}\``,
				);
				continue;
			}
			if (textOf(resolve(root, path)) !== content)
				errors.push(
					`agent-rules: ${path} does not match the pinned CLI plus this repository's declared overlay; run \`bun run ${SYNC_SCRIPT}\``,
				);
		}
	}

	// The vendor's own archive procedure must appear NOWHERE. Replacing it in the
	// two artifacts that shipped it is not enough: the point is that no agent
	// reading anything in this tree is ever told to move the directory itself.
	for (const path of grepTracked(root, FORBIDDEN_VENDOR_PROCEDURE)) {
		errors.push(
			`agent-rules: ${path} describes the vendor archive procedure; archiving goes through the wrapper`,
		);
	}

	// Wiring. A guard nothing runs is documentation.
	for (const path of [GUARD_CONTRACT, GUARD_ENTRYPOINT, SYNC_ENTRYPOINT]) {
		if (!exists(resolve(root, path)))
			errors.push(`agent-rules: ${path} is missing`);
	}
	const manifest = resolve(root, "package.json");
	if (exists(manifest)) {
		const value = JSON.parse(textOf(manifest)) as JsonRecord;
		const scripts =
			typeof value["scripts"] === "object" && value["scripts"] !== null
				? (value["scripts"] as Record<string, unknown>)
				: {};
		if (scripts[GUARD_SCRIPT] !== `bun ${GUARD_ENTRYPOINT}`)
			errors.push(
				`agent-rules: package script ${GUARD_SCRIPT} must run ${GUARD_ENTRYPOINT}`,
			);
		if (scripts[SYNC_SCRIPT] !== `bun ${SYNC_ENTRYPOINT}`)
			errors.push(
				`agent-rules: package script ${SYNC_SCRIPT} must run ${SYNC_ENTRYPOINT}`,
			);
	}
	return [...new Set(errors)].sort();
}
