import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	CANONICAL_FILE,
	planMirrors,
	regenerateVendorArtifacts,
	sharedBlocks,
	VENDOR_ARTIFACTS,
} from "./agent-rules-contract";

const OPENSPEC_MARKER = "openspec/config.yaml";

/**
 * Regenerate every mirror region from the canonical `AGENTS.md`.
 *
 * This is the ONLY way a mirror is allowed to change. Editing `CLAUDE.md` or
 * `GEMINI.md` by hand produces two rules that agree until the day one of them
 * is updated, and `rules:check` exists to make that day today rather than
 * whenever somebody notices.
 *
 * `--check` reports what would change without writing, which is what the guard
 * and the tests use to prove the generator is idempotent.
 */
export async function syncAgentRules(
	root = resolve(import.meta.dir, "../.."),
	options: { write?: boolean } = {},
): Promise<{ changed: string[] }> {
	const canonical = sharedBlocks(
		readFileSync(resolve(root, CANONICAL_FILE), "utf8"),
	);
	if (canonical.errors.length > 0) throw new Error(canonical.errors.join("\n"));
	const changed: string[] = [];
	for (const entry of planMirrors(root, canonical.blocks)) {
		const current = readFileSync(entry.path, "utf8");
		if (current === entry.content) continue;
		changed.push(entry.surface.file);
		if (options.write !== false) await Bun.write(entry.path, entry.content);
	}
	// The generated Claude artifacts, regenerated by spawning the pinned CLI.
	// Only for a tree that has the OpenSpec marker: a project without the
	// capability has no CLI to spawn and no artifacts to own.
	if (await Bun.file(resolve(root, OPENSPEC_MARKER)).exists()) {
		const regenerated = regenerateVendorArtifacts(root);
		if (regenerated.errors.length > 0)
			throw new Error(regenerated.errors.join("\n"));
		for (const path of VENDOR_ARTIFACTS) {
			const content = regenerated.files.get(path);
			if (content === undefined) continue;
			const target = resolve(root, path);
			const current = (await Bun.file(target).exists())
				? readFileSync(target, "utf8")
				: undefined;
			if (current === content) continue;
			changed.push(path);
			if (options.write !== false) await Bun.write(target, content);
		}
	}
	return { changed };
}

if (import.meta.main) {
	const check = process.argv.includes("--check");
	const result = await syncAgentRules(resolve(import.meta.dir, "../.."), {
		write: !check,
	});
	if (result.changed.length === 0) {
		console.log(`Agent rule mirrors are current with ${CANONICAL_FILE}.`);
	} else if (check) {
		console.error(
			`Agent rule mirrors have drifted from ${CANONICAL_FILE}:\n- ${result.changed.join("\n- ")}`,
		);
		process.exit(1);
	} else {
		console.log(
			`Regenerated from ${CANONICAL_FILE}:\n- ${result.changed.join("\n- ")}`,
		);
	}
}
