#!/usr/bin/env bash
# Idempotent, bounded Codex Cloud setup and maintenance.
#
# The hosted environment runs this file as both its setup command and its
# maintenance command, so every step must be safe to repeat: tool installs are
# version-gated, the shell hook is appended once, persisted secrets are upserted
# rather than rewritten, and the run ends by recording a fingerprint and
# self-verifying through the doctor.

set -euo pipefail

CLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$CLOUD_DIR/lib.sh"

log() {
	echo "Codex cloud bootstrap: $*"
}

fail() {
	echo "Codex cloud bootstrap: $*" >&2
	exit 1
}

profile="${1:-}"
if [ -z "$profile" ]; then
	profile="$(cloud_contract_value default_profile)"
fi
case "$profile" in
	core) ;;
	# capability:start playwright
	browser) ;;
	# capability:end playwright
	*)
		echo "Codex cloud bootstrap: unsupported profile '${profile}'" >&2
		echo "Usage: bash .codex/cloud/bootstrap.sh [profile]" >&2
		exit 2
		;;
esac

if [ "$(uname -s)" != "Linux" ]; then
	fail "only Linux environments are supported"
fi

attempts="$(cloud_contract_value network_attempts)"
timeout_seconds="$(cloud_contract_value network_timeout_seconds)"

# Bounded retry for every network-dependent step. Each attempt is wrapped in a
# hard timeout so a hung mirror cannot stall the hosted setup phase.
retry_command() {
	local label="$1"
	local attempt_limit="$2"
	local attempt_timeout="$3"
	shift 3
	if ! printf '%s' "$attempt_limit" | grep -Eq '^[1-9][0-9]*$'; then
		fail "invalid attempt count '${attempt_limit}' for ${label}"
	fi
	if ! printf '%s' "$attempt_timeout" | grep -Eq '^[1-9][0-9]*$'; then
		fail "invalid timeout '${attempt_timeout}' for ${label}"
	fi
	local attempt=1
	local status
	while [ "$attempt" -le "$attempt_limit" ]; do
		status=0
		timeout "$attempt_timeout" "$@" || status=$?
		if [ "$status" -eq 0 ]; then
			return 0
		fi
		echo "Codex cloud bootstrap: ${label} failed (attempt ${attempt}/${attempt_limit}, exit ${status})" >&2
		if [ "$attempt" -lt "$attempt_limit" ]; then
			sleep 5
		fi
		attempt=$((attempt + 1))
	done
	fail "${label} failed after ${attempt_limit} attempts"
}

# Codex Cloud exposes secrets to the setup and maintenance phases only and
# strips them before the agent phase. Copy each allow-listed variable that is
# set right now into a 0600 file the persisted environment sources, and upsert
# instead of rewriting: this script also runs in the agent phase, where a
# rewrite would erase every genuinely stripped value. Values are never echoed.
persist_cloud_secrets() {
	local secrets_file
	local directory
	local name
	local names=""
	local prior
	local staged
	local count=0

	secrets_file="$(cloud_persisted_secrets_file)"
	directory="$(dirname "$secrets_file")"
	mkdir -p "$directory"

	for name in $(cloud_contract_list secret_allow_list) $(printf '%s' "${CODEX_CLOUD_PERSIST_EXTRA_ENV:-}" | tr ',' ' '); do
		if printf '%s' "$name" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*$'; then
			names="${names} ${name}"
		fi
	done

	prior="$(mktemp)"
	staged="$(mktemp "${directory}/.codex-cloud-secrets.XXXXXX")"
	if [ -r "$secrets_file" ]; then
		cat "$secrets_file" >"$prior"
	fi

	for name in $names; do
		# ${name+x} keeps a deliberately empty value distinguishable from unset.
		if eval "[ -n \"\${${name}+x}\" ]"; then
			eval "printf 'export %s=%q\n' \"\$name\" \"\$${name}\"" >>"$staged"
			count=$((count + 1))
		else
			grep -E "^export ${name}=" "$prior" | tail -n 1 >>"$staged" || true
		fi
	done

	sort -u "$staged" -o "$staged"
	chmod 0600 "$staged"
	mv -f "$staged" "$secrets_file"
	rm -f "$prior"
	log "persisted ${count} cloud secrets"
}

export PROTO_HOME="${PROTO_HOME:-$HOME/.proto}"
export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$HOME/.local/bin:$HOME/.bun/bin:$PATH"
for tool in $(cloud_contract_list required_tools); do
	tool_version="$(cloud_tool_version "$tool")"
	tool_variable="PROTO_$(printf '%s' "$tool" | tr '[:lower:]' '[:upper:]')_VERSION"
	eval "export ${tool_variable}=\"\${tool_version}\""
done

# Fresh, non-interactive cloud shells do not inherit this process environment,
# so record it once and source it from ~/.bashrc and from every entry point.
persisted_env="$(cloud_persisted_environment_file)"
persisted_secrets="$(cloud_persisted_secrets_file)"
mkdir -p "$(dirname "$persisted_env")"
{
	printf '%s\n' '# Generated by .codex/cloud/bootstrap.sh. Do not edit by hand.'
	printf '%s\n' 'export CODEX_CLOUD=true'
	printf 'export %s=%s\n' "$(cloud_contract_value profile_environment_variable)" "$profile"
	printf '%s\n' 'export PROTO_HOME="$HOME/.proto"'
	printf '%s\n' 'export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$HOME/.local/bin:$HOME/.bun/bin:$PATH"'
	# capability:start playwright
	if [ "$profile" = "$(cloud_contract_value browser_profile)" ]; then
		printf 'export %s=%s\n' \
			"$(cloud_contract_value browser_environment_variable)" \
			"$(cloud_expand_home "$(cloud_contract_value browser_payload_root)")"
	fi
	# capability:end playwright
	printf 'if [ -r "%s" ]; then . "%s"; fi\n' "$persisted_secrets" "$persisted_secrets"
} >"$persisted_env"

touch "$HOME/.bashrc"
source_line=". \"${persisted_env}\""
if ! grep -Fqx "$source_line" "$HOME/.bashrc"; then
	printf '\n%s\n' "$source_line" >>"$HOME/.bashrc"
fi

persist_cloud_secrets || echo "Codex cloud bootstrap: unable to persist cloud secrets" >&2

# Proto is installed by the one shared, checksum-pinned installer named in the
# contract's proto_installer key. There is no parallel cloud-only installer.
proto_expected="$(cloud_tool_version proto)"
if [ "$(cloud_actual_tool_version proto)" != "$proto_expected" ]; then
	retry_command "installing Proto ${proto_expected}" "$attempts" "$timeout_seconds" \
		bash "$REPO_ROOT/$(cloud_contract_value proto_installer)"
	hash -r
	proto_actual="$(cloud_actual_tool_version proto)"
	if [ "$proto_actual" != "$proto_expected" ]; then
		fail "proto version mismatch after install (expected ${proto_expected}, got ${proto_actual:-missing})"
	fi
fi

for tool in $(cloud_contract_list required_tools); do
	if [ "$tool" = "proto" ]; then
		continue
	fi
	tool_version="$(cloud_tool_version "$tool")"
	if [ "$(cloud_actual_tool_version "$tool")" = "$tool_version" ]; then
		continue
	fi
	retry_command "installing ${tool} ${tool_version}" "$attempts" "$timeout_seconds" \
		proto install --yes "$tool" "$tool_version"
done
hash -r

for tool in $(cloud_contract_list required_tools); do
	tool_version="$(cloud_tool_version "$tool")"
	tool_actual="$(cloud_actual_tool_version "$tool")"
	if [ "$tool_actual" != "$tool_version" ]; then
		fail "${tool} version mismatch (expected ${tool_version}, got ${tool_actual:-missing})"
	fi
done

# capability:start graphify
graphify_version="$(cloud_contract_value graphify_version)"
graphify_binary="$(cloud_contract_value graphify_binary)"
if [ "$(cloud_actual_tool_version "$graphify_binary")" != "$graphify_version" ]; then
	retry_command "installing $(cloud_contract_value graphify_package) ${graphify_version}" \
		"$attempts" "$timeout_seconds" \
		uv tool install --force "$(cloud_contract_value graphify_package)==${graphify_version}"
	hash -r
fi
graphify_actual="$(cloud_actual_tool_version "$graphify_binary")"
if [ "$graphify_actual" != "$graphify_version" ]; then
	fail "${graphify_binary} version mismatch (expected ${graphify_version}, got ${graphify_actual:-missing})"
fi
# capability:end graphify

cd "$REPO_ROOT"
frozen_dependency_command="$(cloud_contract_value frozen_dependency_command)"
# shellcheck disable=SC2086
retry_command "frozen dependency install" "$attempts" "$timeout_seconds" $frozen_dependency_command

# capability:start playwright
if [ "$profile" = "$(cloud_contract_value browser_profile)" ]; then
	browser_root="$(cloud_expand_home "$(cloud_contract_value browser_payload_root)")"
	browser_version="$(cloud_contract_value browser_playwright_version)"
	browser_timeout="$(cloud_contract_value browser_network_timeout_seconds)"
	browser_arguments="$(cloud_contract_value browser_install_command)"
	eval "export $(cloud_contract_value browser_environment_variable)=\"\${browser_root}\""
	mkdir -p "$browser_root"
	# Operating-system packages are only installable where this host already
	# grants passwordless privilege escalation.
	if sudo -n true >/dev/null 2>&1; then
		browser_arguments="${browser_arguments/install/install --with-deps}"
	fi
	# shellcheck disable=SC2086
	retry_command "installing the browser payload ${browser_version}" \
		"$attempts" "$browser_timeout" \
		bunx "playwright@${browser_version}" $browser_arguments
	printf '%s\n' "$browser_version" \
		>"${browser_root}/$(cloud_contract_value browser_marker_basename)"
fi
# capability:end playwright

marker_file="$(cloud_marker_file "$profile")"
mkdir -p "$(dirname "$marker_file")"
cloud_contract_fingerprint "$profile" >"$marker_file"

# Bootstrap can never report success while the doctor would refuse the tree.
CODEX_CLOUD=true CODEX_CLOUD_PROFILE="$profile" bash "$CLOUD_DIR/doctor.sh"

log "prepared the ${profile} profile"
