#!/usr/bin/env bash
set -e

echo "🤖 Configuring repository-local OpenSpec..."

# Source common setup functions
source /workspace/.devcontainer/on-create/setup-common.sh

# Setup Proto environment to access bun
setup_proto_env

if [ ! -x /workspace/node_modules/.bin/openspec ]; then
    echo "Repository-local OpenSpec is missing after dependency installation" >&2
    return 1
fi

# No `openspec init` here — committed artifacts are the source of truth.
#
# The repository commits the experimental artifact workflow for Claude
# (.claude/skills/openspec-*/ and .claude/commands/opsx/), generated by
# `openspec artifact-experimental-setup` against the pinned CLI. Regenerate
# them in the template repo and commit the diff; never at container create.
#
# `openspec init` writes the *other*, non-experimental family — openspec/AGENTS.md,
# openspec/project.md, .claude/commands/openspec/, and an OPENSPEC managed block
# injected into AGENTS.md and CLAUDE.md. Running it at create time gave every
# container a second, uncommitted set of slash commands under different names.
# (The previous invocation also passed `--force`, which 0.19.0 rejects as an
# unknown option — this step has been failing since the pin.)
#
# The CLI needs no init to work: openspec/config.yaml is the initialization
# marker, and it is a committed, capability-gated artifact. Verify it and stop.
if [ ! -f /workspace/openspec/config.yaml ]; then
    echo "openspec/config.yaml is missing; the OpenSpec CLI has no project config" >&2
    return 1
fi

echo "✅ Repository-local OpenSpec configured!"
